### ISSUE TITLE
eval_eqn pops arguments twice in NodeIf

### ISSUE THREAD

**Issue by lacava** [lacava/feat#110]
https://github.com/lacava/feat/blob/ef3efd3c1e71a8c3b5564b7f793690658a7cf398/src/node/nodeif.h#L35

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/b49ef2ff979df242b6c24d99835f081d233e50ea

**Comment by lacava** [comment]
looks good. please make these changes on a separate branch and issue a PR
