### ISSUE TITLE
Stack class comments

### ISSUE THREAD

**Issue by lacava** [lacava/feat#111]
first question: should this be an extension of `std::vector<type>`, rather than having a private `vector<type>` member? that might simplify things. 

second, there are no comments! please comment the code.

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/7d4d13f1a9e437005a5c1c233de0c1fbaf3cdde8

**Comment by lacava** [comment]
looks good, please send a PR on an appropriate branch
