### ISSUE TITLE
max_time option

### ISSUE THREAD

**Issue by lacava** [lacava/feat#122]
implement option to end based on runtime rather than number of iterations/generations.

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/7b5f9491f6e0bb4bc594d2be1e494589b661aff1

Still left to change printing of stats and progress bar

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/01bfea2865a2665c5e0ee2611bbb608746b07047
change in progress bar when using max_time option

**Comment by lacava** [comment]
see #167

**Comment by lacava** [comment]
max_time hasn't been added to Feat() constructor, nor has it been added to the python wrapper. Reopening until these are fixed.

**Comment by lacava** [comment]
fixed
