### ISSUE TITLE
remove extraneous variable definitions in Node evaluate

### ISSUE THREAD

**Issue by lacava** [lacava/feat#132]
e.g. do this 
`stack.f.push(stack.f.pop() - stack.f.pop())`
instead of this
    ArrayXd x1 = stack.f.pop();
    ArrayXd x2 = stack.f.pop();
    stack.f.push(x1 - x2)

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/ddfca49177c369ae1c257d6fe238a3b7f3e1aa49
