### ISSUE TITLE
stochastic mini-batch training

### ISSUE THREAD

**Issue by lacava** [lacava/feat#160]
add the ability to train on random subsets of the training data each generation.

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/e8bc6cfad62b869ceeda4558727e3e5f698b66be, https://github.com/lacava/feat/commit/7eba595eaba0e2b7726a0a596a64bda9b4d0841d and https://github.com/lacava/feat/commit/f8e39a5edb3d6cf0b8c6ce6ae814012f458b18b6

still errors in assign_fit in evaluation class when running on multiple threads
