### ISSUE TITLE
categorical / integer stack

### ISSUE THREAD

**Issue by lacava** [lacava/feat#172]
add a stack type for integers/ categorical features. Any feature with less than 10 unique values should be treated as categorical. operators that work on ints will need to be written as well.

**Comment by lacava** [comment]
nodes that use categorical types: 

 - [ ] NodeVariable
 - [ ] NodeSplit (make categorical version that splits on categorical values for threshold) 
 - [ ] NodeFloat (version that converts categorical data to floating data)

**Comment by tilakhere** [comment]
categorical stack without template functions
https://github.com/lacava/feat/commit/447fed04a634a988480985a2cde7d38b41e090da

need to discuss ways to implement template stacks
