### ISSUE TITLE
error in CMulticlassLogisticRegression, final model seg fault

### ISSUE THREAD

**Issue by lacava** [lacava/feat#174]
I'm getting a seg fault on the allbp.csv dataset running ./build/feat examples/allbp.csv --c --use_batch 

from @tilakhere 
> the segmentation fault seems to be coming in classification problems in get_w() function of ML.h. The issue is in get_w() of CMulticlassLogisticRegression as far I have followed it till now.
> I am also facing this problem on master branch with this same file while trying to print the final model.

**Comment by lacava** [comment]
@tilakhere where are we at with this bug?

**Comment by lacava** [comment]
this is mostly due to the imbalance of the dataset, which has only 14 0 class sampels (less than 1%). Because of this the main function train/test split was missing a class during training.

**Comment by tilakhere** [comment]
issue fixed commit https://github.com/lacava/feat/commit/55a693a1065a1a5ed5b450c80d5dd44f145f4609

Needed to replace get_num_classes() with get_num_machines() in get_w() of CMulticlassLogisticRegression.
