### ISSUE TITLE
Organize code into namespaces

### ISSUE THREAD

**Issue by lacava** [lacava/feat#195]
the src/ folder is getting pretty long, and I think it's time we did some housekeeping and organized the code a little better. At the moment we just have a single namespace FT. I would like to instead have **a namespace structure that mirrors a folder structure**. I propose something like this:

FT::
 - feat.cc/h
 - main.cc/h
 - init.h
 - params.cc/h
 - [x] Sel::
   - selection.cc/h
   - everything in selection/
 - [x] Eval::
   - evaluation.cc/h
   - metrics.cc/h
- [x] Pop::
   - population.cc/h
   - individual.cc/h
   - nodevector.cc/h
   - archive.cc/h
   - nodewrapper.h
   - [ ] Op::
      - everything in node/
- [x] Util::
   - utils.cc/h
   - io.cc/h
   - error.cc/h
   - rnd.cc/h
- [x] Opt::
   - hillclimb.cc/h
   - auto_backprop.cc/h
- [x] Model::
   - ml.cc/h
   - everything in ml/
- [x] Vary::
   - variation.cc/h
- [x] Dat::
   - data.cc/h
   - stack.cc/h

Each of these namespaces would have a corresponding folder in src/, named as the lowercase version of the namespace.

**Comment by tilakhere** [comment]
Initial commit https://github.com/lacava/feat/commit/02598411c013b321f8659b8399b124ceafc6ba6b

@lacava Need suggestions for following namespaces (temporary names -- need to be changed)

Data -> DataSpace
ML -> MLSpace
Selection -> SelectionSpace
Node -> NodeSpace

Also in ML folder the files 

 MulticlassLogisticRegression.cc
 MulticlassLogisticRegression.h
 MyCARTree.cc
 MyCARTree.h
 MyCARTreeNodeData.cc
 MyCARTreeNodeData.h
 MyLibLinear.cc
 MyLibLinear.h
 MyMulticlassLibLinear.cc
 MyMulticlassLibLinear.h

are all under shogun namesapce....should they be nested under ML namespace?
