### ISSUE TITLE
mkdocs documentation

### ISSUE THREAD

**Issue by lacava** [lacava/feat#198]
switching over to mkdocs for documentation (see readthedocs and builddocs branches). the goal is to use travis to build the documentation on the master branch. 

@lacava will work on the docs and @tilakhere will work on the travis integration.

**Comment by tilakhere** [comment]
travis integration done. commit https://github.com/lacava/feat/commit/da31e5c4ae29f5c86958d8fc821165c14e8a34ad

**Comment by lacava** [comment]
seems to be working now.
