### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by lacava** [lacava/feat#200]
- [x] remove featCV cross validation 
- [x] remove extra backprop cost function pointers and methods
- [x] update resultant docs

**Comment by tilakhere** [comment]
removed CV cross validation https://github.com/lacava/feat/commit/e1a64c0a8aa6b791b0901d40869f10cacf6c662d

removed featcv documentation
https://github.com/lacava/feat/commit/c12eeee6cabee7ef542f3b343fd184ede1c80b67
