### ISSUE TITLE
store log information in class object

### ISSUE THREAD

**Issue by lacava** [lacava/feat#201]
- [x] store information about training loss and other variables that are normally output by the logging options as a member of feat so that the python wrapper can access training information.

- [x] include stats function dictionary in python wrapper

- [x] write test in python to assert for size of log info

**Comment by tilakhere** [comment]
storing stats in feat obj - commit https://github.com/lacava/feat/commit/ae0f09c45560a9157213cd9f4ee5a5e9538d4b8b

stats function - dict commit https://github.com/lacava/feat/commit/53454499276fd0d3efa68d94c5dc68748ff72227

python test - commit https://github.com/lacava/feat/commit/b4a177d4be07e1f99b7e83d83f2ded86458185b7 and https://github.com/lacava/feat/commit/33bd14a9e36b5fda5fe8f14eda8c7620a08fcd76

fixing some other errors in above listed commits - commit https://github.com/lacava/feat/commit/49216599683c5cc0ed9be8ae33cac9709aac530f
