### ISSUE TITLE
clean up stratify split printout

### ISSUE THREAD

**Issue by lacava** [lacava/feat#225]
only print stratify split results with verbosity > 2

**Comment by tilakhere** [comment]
Created a logger class instead to be used by all other classes. Removed params.msg to this logger class

commit https://github.com/lacava/feat/commit/fec5d7ec3f752279a21ee85ad986748b4d420f8f & https://github.com/lacava/feat/commit/f846afee344c6575a5a3f1ce5e24ed20559d8cba
