### ISSUE TITLE
using bal_zero_one on 2 class problem

### ISSUE THREAD

**Issue by lacava** [lacava/feat#226]
from Issue #219 
> Why "bal_zero_one" metric is not compatible with 2-class classification problem ? I needed to change
> "SGVector _tmp = dynamic_pointer_castsh::CMulticlassLabels(labels)->get_labels()" for
> "SGVector _tmp = dynamic_pointer_castsh::CBinaryLabels(labels)->get_labels()" to make it work.

**Comment by tilakhere** [comment]
fixed commit https://github.com/lacava/feat/commit/04daa4b0166ad83bdf0482665af8a9639e98dfc5
