### ISSUE TITLE
Split operation does not re-evaluate following point mutation

### ISSUE THREAD

**Issue by PCRLee** [lacava/feat#241]
Hi,

I noticed that the split operation does not re-evaluate to find the best threshold after point mutation in the terminal node. 

For example: 

```
[X<3.5](X split)
point mutation
		mutating node X
mutating [Y<3.5](Y split)
assigning Y split...
```

Here, the Y threshold will be set as 3.5 (the previous X threshold) even when it is not the appropriate threshold for Y according to the split operator. As a result, I'm seeing split operations with suboptimal thresholds.

Thank you!

**Comment by lacava** [comment]
Is this taken from the terminal output during variation? The variation step does not re-evaluate any of the nodes, but all of the offspring are re-evaluated in the [following step](https://github.com/lacava/feat/blob/master/src/feat.cc#L561):

```
 // variation to produce offspring
 logger.log("variation...", 3);
 p_variation->vary(*p_pop, parents, params,*d.t);
 logger.log("offspring:\n" + p_pop->print_eqns(true), 3);

 // evaluate offspring
 logger.log("evaluating offspring...", 3);
 p_eval->fitness(p_pop->individuals, *d.t, F, params, true && !params.use_batch);
```

if you track the invidual thru that step you should see the threshold update. if not, please follow up here.

**Comment by lacava** [comment]
closing after discussion. note also that we fixed a bug in thresholds for classification in commit cd56b34c23ddd0ab08b43b1a6ad2736e95520d2e
