### ISSUE TITLE
Eigen is not at bitbucket anymore

### ISSUE THREAD

**Issue by folivetti** [lacava/feat#265]
you might want to update your documentation, Eigen is now at https://gitlab.com/libeigen/eigen

**Comment by folivetti** [comment]
also, feat is not compatible with the current version 3.3.90

**Comment by lacava** [comment]
eigen is now installed via conda with version 3.3.7 in PR #267. We should open a separate issue about 3.3.9, I'm not sure about it; the conda package version is 3.3.7 and works.
