### ISSUE TITLE
FewtwoCV

### ISSUE THREAD

**Issue by lacava** [lacava/feat#64]
Write a crossvalidation wrapper for fewtwo.

**Comment by lacava** [comment]
would be good to specify a vector of structs, like the list of dicts that gridsearchCV is able to use; 
```
hyper_params = [{
        'popsize': (500,), 'g': (2000,),
        'max_len': (25, 50, 100),
        'rt_cross':(0.2,),'rt_mut':(0.8,),
    },  
    {   
        'popsize': (1000,),'g':(1000,), 
        'max_len': (25, 50, 100),
        'rt_cross':(0.5,), 'rt_mut':(0.5,),
    },  
    {   
        'popsize': (2000,),'g':(500,),
        'max_len': (25, 50, 100),
        'rt_cross':(0.8,),'rt_mut':(0.2,),
    },  
    {   
        'popsize': (500,), 'g': (2000,),
        'max_len': (25, 50, 100),
        'rt_cross':(0.2,),'rt_mut':(0.8,),
    },  
    {   
        'popsize': (1000,),'g':(1000,), 
        'max_len': (25, 50, 100),
        'rt_cross':(0.5,), 'rt_mut':(0.5,),
    },  
    {   
        'popsize': (2000,),'g':(500,),
        'max_len': (25, 50, 100),
        'rt_cross':(0.8,),'rt_mut':(0.2,),
    },  

]
```

**Comment by lacava** [comment]
parameters to vary : 

```
- [ ] int pop_size=100, 
- [ ] int gens = 100, 
- [ ] string ml = "LinearRidgeRegression",           
- [ ] int max_stall = 0,               
- [ ] string sel ="lexicase", 
- [ ] string surv="pareto", 
- [ ] float cross_rate = 0.5,            
- [ ] string functions = "+,-,*,/,^2,^3,exp,log,and,or,not,=,<,>,ite", 
- [ ] unsigned int max_depth = 3, 
- [ ] unsigned int max_dim = 10,      
- [ ] bool erc = false, 
- [ ] string obj="fitness,complexity",          
- [ ] double fb=0.5
```

**Comment by lacava** [comment]
@tilakhere can you check off each of these, assuming they are implemented. 

Also, can you clean up cv_main.cc so the command line options aren't there? 

It would also be good to add a section to the Examples for how to use the CV wrapper, explaining the string syntax. then we can close this issue.

**Comment by tilakhere** [comment]
Changes done

Add input file for hyper params and clean up of cv_main.cc commit https://github.com/lacava/feat/commit/cb05c19c2ea83ca17f9c55d02f9b5e1b75629cef

Add example in example.md commit https://github.com/lacava/feat/commit/ee34a88c82b4d0a41aa6e86c1a49ec088a473ca7

Improve parallel loop to use tasks instead of breaking loop into chunks to increase cpu utilization commit https://github.com/lacava/feat/commit/05320cc5a2547141718cc68535b2ba9125d86c3d
