### ISSUE TITLE
longitudinal data nodes

### ISSUE THREAD

**Issue by lacava** [lacava/feat#74]
add nodes to process longitudinal data. these nodes represent multi-dimensional data from the ehr. 

- [x] long variable node ( 1)  
- [x] mean ( 1) 
- [x] median (1)
- [x] max (1)
- [x] min (1)
- [x] var (2 )
- [x] skew (3)
- [x] kurtosis (4)
- [x] slope(4) (covariance(time, y)/variance(y))
- [x] count (1) : returns count of readings
- [x] recent (1) : returns the most recent reading (should be merged with time ?  comment for time node - by default, return the latest measurment. returns data with a set time delay, initialized during construction. if the delay is longer than the data, return last. )

**Comment by tilakhere** [comment]
commit https://github.com/lacava/feat/commit/f07b4e400f7ef5759409ceb7b88aae4d91f4bd58

time node left

**Comment by lacava** [comment]
ah. we should remove the one from node2dgasusian.h.

**Comment by tilakhere** [comment]
removed `variance()` from node2dgausian and used the one in utils.h everywhere
