### ISSUE TITLE
cuda versions of nodes

### ISSUE THREAD

**Issue by lacava** [lacava/feat#78]
we need to write cuda versions of nodes so that their evaluation is done on the GPU. A good example of this is https://github.com/GPMueller/eigen-cuda

basic steps:

- [x] For each node, write a cuda version to a new file. It should include a wrapper function that calls the gpu as in the example above.
- [x] use a pragma definition to determine whether the node is included in the build (USE_CUDA)

node list:
- [x] node2dgaussian.cu
- [x] nodeadd.cu
- [x] nodeand.cu
- [x] nodeconstant.cu
- [x] nodecos.cu
- [x] nodecube.cu
- [x] nodedivide.cu
- [x] nodeequal.cu
- [x] nodeexponent.cu
- [x] nodeexponential.cu
- [x] nodegaussian.cu
- [x] nodegeq.cu
- [x] nodegreaterthan.cu
- [x] node.cu
- [x] nodeif.cu
- [x] nodeifthenelse.cu
- [x] nodeleq.cu
- [x] nodelessthan.cu
- [x] nodelog.cu
- [x] nodelogit.cu
- [x] nodemultiply.cu
- [x] nodenot.cu
- [x] nodeor.cu
- [x] noderoot.cu
- [x] nodesign.cu
- [x] nodesin.cu
- [x] nodesqrt.cu
- [x] nodesquare.cu
- [x] nodestep.cu
- [x] nodesubtract.cu
- [x] nodetanh.cu
- [x] nodevariable.cu
- [x] nodexor.cu
- [x] n_count.cu
- [x] n_float.cu
- [x] n_kurtosis.cu
- [x] n_longitudinal.cu
- [x] n_max.cu
- [x] n_mean.cu
- [x] n_median.cu
- [x] n_min.cu
- [x] n_mode.cu
- [x] n_relu.cu
- [x] n_skew.cu
- [x] n_slope.cu
- [x] n_split.cu
- [x] n_time.cu
- [x] n_var.cu

**Comment by lacava** [comment]
started on https://github.com/lacava/feat/tree/cuda

**Comment by lacava** [comment]
node list:
- [ ] node2dgaussian.cu
- [ ] nodeadd.cu
- [ ] nodeand.cu
- [ ] nodeconstant.cu
- [ ] nodecos.cu
- [ ] nodecube.cu
- [ ] nodedivide.cu
- [ ] nodeequal.cu
- [ ] nodeexponent.cu
- [ ] nodeexponential.cu
- [ ] nodegaussian.cu
- [ ] nodegeq.cu
- [ ] nodegreaterthan.cu
- [ ] node.cu
- [ ] nodeif.cu
- [ ] nodeifthenelse.cu
- [ ] nodeleq.cu
- [ ] nodelessthan.cu
- [ ] nodelog.cu
- [ ] nodelogit.cu
- [ ] nodemultiply.cu
- [ ] nodenot.cu
- [ ] nodeor.cu
- [ ] noderoot.cu
- [ ] nodesign.cu
- [ ] nodesin.cu
- [ ] nodesqrt.cu
- [ ] nodesquare.cu
- [ ] nodestep.cu
- [ ] nodesubtract.cu
- [ ] nodetanh.cu
- [ ] nodevariable.cu
- [ ] nodexor.cu

**Comment by lacava** [comment]
need to add versions of longitudinal nodes

**Comment by tilakhere** [comment]
longitudinal versions added....4 nodes left

**Comment by tilakhere** [comment]
additional nodes added commit https://github.com/lacava/feat/commit/9d22e7794ce27d5e6afab90a72a6faf3977a4675 and https://github.com/lacava/feat/commit/70ddf50555ef2cb329077535212d4175e7b352cf
