### ISSUE TITLE
featcv input file format

### ISSUE THREAD

**Issue by lacava** [lacava/feat#89]
right now the featcv string syntax is 

```
`[{('token1': val1, val2, val3)('token2': val1, val2)}, {('token1': val1, val2, val3)('token2': val1, val2)},]`
```

can we change the hyperparameter input format slightly, to 
```
"[{'token1': (1, 2, 3), 'token2': (1, 2)}, {'token1': (1, 2, 3), 'token2': (1, 2)}]"
```
? then we can literally feed in string conversions of python dictionary lists. e.g.:

```python
$python
>>> d = [{'token1': (1, 2, 3), 'token2': (1, 2)}, {'token1': (1, 2, 3), 'token2': (1, 2)}]
>>> str(d)
"[{'token1': (1, 2, 3), 'token2': (1, 2)}, {'token1': (1, 2, 3), 'token2': (1, 2)}]"
```
that would make the python wrapper much easier to use with featcv.

**Comment by tilakhere** [comment]
done commit https://github.com/lacava/feat/commit/812aa48c2bc59570349d2707f832e2e26ada8b14

**Comment by lacava** [comment]
see PR #91
